---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
    config:
      config: test/fixtures/config/.eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "src/lib/*.js"
exclude_paths:
- test/
- bin/
- scripts/
- lib/
