---
branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
language: node_js
node_js:
  - stable
  - 9
  - 8
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
env:
  global:
    - CXX=g++-4.8
    - CC_TEST_REPORTER_ID=21230ba3bdbb39a3c727e3108d571aab3de79a8f454f742b7adb13e4a816316a
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build -t lcov -p ./test/coverage --exit-code $TRAVIS_TEST_RESULT
