---
branches:
  only:
  - master
  - develop
  - /^greenkeeper/.*$/
language: node_js
node_js:
  - stable
  - 9
  - 8
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
env:
  global:
    - CC_TEST_REPORTER_ID=21230ba3bdbb39a3c727e3108d571aab3de79a8f454f742b7adb13e4a816316a
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ $TRAVIS_NODE_VERSION = stable ]
  && nyc report --reporter=lcov
  && ./cc-test-reporter after-build --debug -t lcov --exit-code $TRAVIS_TEST_RESULT
  || echo 'Coverage skipped'"
