language: node_js
node_js:
  - 4
  - 5
  - stable
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
addons:
    code_climate:
        repo_token: 0bd3e07002a646bda77f9fbd39689fbb4c37ac8cf62e3fa3705f8edbeebbeff8
after_script:
  - nyc report --reporter=text-lcov | codeclimate-test-reporter
